# Generated by Django 3.1.1 on 2020-09-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20200927_0202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dificulty',
            new_name='Difficulty',
        ),
        migrations.RenameField(
            model_name='difficulty',
            old_name='dificultyLevel',
            new_name='difficultyLevel',
        ),
    ]
