# Generated by Django 3.1.1 on 2020-09-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0008_auto_20200927_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionDescription', models.CharField(blank=True, max_length=250, null=True)),
                ('optionA', models.CharField(blank=True, max_length=50, null=True)),
                ('optionB', models.CharField(blank=True, max_length=50, null=True)),
                ('optionC', models.CharField(blank=True, max_length=50, null=True)),
                ('optionD', models.CharField(blank=True, max_length=50, null=True)),
                ('answere', models.CharField(blank=True, max_length=1, null=True)),
                ('answereDescription', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.topic')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.difficulty')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.source')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subject')),
            ],
        ),
    ]
