# Generated by Django 3.1.1 on 2020-09-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/BackgroundArt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
