# Generated by Django 3.1.1 on 2020-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_art', '0002_backgroundart'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundart',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='backgroundart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/BackgroundArt'),
        ),
    ]
