# Generated by Django 3.1.1 on 2020-10-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featured_art', '0003_auto_20200929_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundArt',
        ),
    ]
